version: "2"

run:
  timeout: 3m

linters-settings:
  presets:
    - bugs
    - unused
  disable-all: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0