ALTER TABLE users
DROP COLUMN state TEXT DEFAULT 'active';

ALTER TABLE users
DROP COLUMN google_id TEXT UNIQUE;

ALTER TABLE users
ALTER COLUMN user_name SET NOT NULL;

ALTER TABLE users
ALTER COLUMN password SET NOT NULL;