DROP TABLE IF EXISTS recipes_ingredients CASCADE;

DROP TABLE IF EXISTS ingredient CASCADE;

DROP TABLE IF EXISTS instruction CASCADE;

DROP TABLE IF EXISTS recipe CASCADE;

DROP TABLE IF EXISTS nutrition CASCADE;
